### ISSUE TITLE
Cannot import models without bones such as stages

### ISSUE THREAD

**Issue by imod-commission** [ssbucarlos/smash-ultimate-blender#119]
When importing models without bones/stages, the following error occur:

Python: Traceback (most recent call last):
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\smash-ultimate-blender-anim_test\panels\import_model.py", line 165, in execute
    import_model(self,context)
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\smash-ultimate-blender-anim_test\panels\import_model.py", line 192, in import_model
    armature = create_armature(ssbh_skel, context)
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\smash-ultimate-blender-anim_test\panels\import_model.py", line 336, in create_armature
    heirarchy_order(edit_bones[0], reordered)
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

location: <unknown location>:-1

**Comment by ScanMountGoat** [comment]
You're not using the latest version of the addon. This has already been fixed. Reinstall following the instructions on the README.
