### ISSUE TITLE
blender 4.0 problem plugin ?

### ISSUE THREAD

**Issue by taz9446** [ssbucarlos/smash-ultimate-blender#230]
bpy.data.window_managers["WinMan"].addon_search = "smas"
Traceback (most recent call last):
  File "F:\torrent\blender-4.0.0-windows-x64\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "F:\torrent\blender-4.0.0-windows-x64\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'smash-ultimate-blender-1'

**Comment by ScanMountGoat** [comment]
Are you using the Blender 4.0 compatible release? If you want to use the latest release, you'll need to use Blender 4.1 or newer. This is the most recent release that supports 4.0: https://github.com/ssbucarlos/smash-ultimate-blender/releases/tag/v1.3.6

**Comment by taz9446** [comment]
> ¿Estás usando la versión compatible con Blender 4.0? Si quieres usar la última versión, tendrás que usar Blender 4.1 o una versión más reciente. Esta es la versión más reciente compatible con 4.0: https://github.com/ssbucarlos/smash-ultimate-blender/releases/tag/v1.3.6

Traceback (most recent call last):
  File "F:\torrent\blender-4.1.0-windows-x64\blender-4.1.0-windows-x64\4.1\scripts\modules\addon_utils.py", line 444, in enable
    mod.register()
  File "C:\Users\Daniel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\smash-ultimate-blender\__init__.py", line 27, in register
    check_unsupported_blender_versions()
  File "C:\Users\Daniel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\smash-ultimate-blender\__init__.py", line 20, in check_unsupported_blender_versions
    raise ImportError("Can't use a Blender version newer than 4.1, please use blender 4.0 or download a 4.1+ compatible version")
ImportError: Can't use a Blender version newer than 4.1, please use blender 4.0 or download a 4.1+ compatible version

With version 4.1 I get this other error

**Comment by ScanMountGoat** [comment]
Are you using this version with Blender 4.1? The latest release appears to only support Blender 4.2 or newer.
https://github.com/ssbucarlos/smash-ultimate-blender/releases/tag/v2.0.1
